server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /common/ { try_files $uri =404; }
  location /academico/ { try_files $uri $uri/ /academico/index.html; }
  location /financiero/ { try_files $uri $uri/ /financiero/index.html; }
  location /docente/ { try_files $uri $uri/ /docente/index.html; }
  location /dashboard/ { try_files $uri $uri/ /dashboard/index.html; }
  location / { try_files $uri $uri/ /index.html; }
}
